name: Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.5'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build app
      run: go build -o myapp
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: myapp